-- Placeholder setting for the read-only Admin API Key.
-- The actual key is generated by the settings service and shown once.
INSERT INTO settings (key, value)
VALUES ('admin_api_key_read_only', '')
ON CONFLICT (key) DO NOTHING;
